/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AttendanceTable: typeof import('./components/table/attendanceTable.vue')['default']
    CustomFooter: typeof import('./components/shared/customFooter.vue')['default']
    CustomHeader: typeof import('./components/shared/customHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    JobApp: typeof import('./components/jobs/job-app.vue')['default']
    JobsCard: typeof import('./components/jobs/components/jobsCard.vue')['default']
    LoginForm: typeof import('./components/auth/components/loginForm.vue')['default']
    MainContent: typeof import('./components/home/components/main-content/mainContent.vue')['default']
    ModalCreatePost: typeof import('./components/works/components/ModalCreatePost.vue')['default']
    PostJobForm: typeof import('./components/home/components/post-job/postJobForm.vue')['default']
    ProfileCard: typeof import('./components/home/components/profile-card/profileCard.vue')['default']
    ProfileForm: typeof import('./components/auth/components/profileForm.vue')['default']
    PublicationForm: typeof import('./components/works/components/publicationForm.vue')['default']
    QRComponent: typeof import('./components/QR/QR-component.vue')['default']
    RegisterForm: typeof import('./components/register/registerForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedJobs: typeof import('./components/jobs/components/savedJobs.vue')['default']
    SearchHeader: typeof import('./components/table/searchHeader.vue')['default']
    Table: typeof import('./components/table/index.vue')['default']
    Tableeader: typeof import('./components/table/tableeader.vue')['default']
    TableHeader: typeof import('./components/table/tableHeader.vue')['default']
    UpdateProfileForm: typeof import('./components/auth/components/updateProfileForm.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
